<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="3" failed="2" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Job is done]]>
    </line>
    <line>
      <![CDATA[Job is done]]>
    </line>
    <line>
      <![CDATA[Job is done]]>
    </line>
    <line>
      <![CDATA[Job is done]]>
    </line>
  </reporter-output>
  <suite started-at="2024-02-27T08:59:22 IST" name="Default suite" finished-at="2024-02-27T08:59:37 IST" duration-ms="15070">
    <groups>
    </groups>
    <test started-at="2024-02-27T08:59:22 IST" name="Default test" finished-at="2024-02-27T08:59:37 IST" duration-ms="15070">
      <class name="package_name.Login_functionality22">
        <test-method signature="StartBrowser(java.lang.String)[pri:0, instance:package_name.Login_functionality22@6771beb3]" started-at="2024-02-27T08:59:22 IST" name="StartBrowser" finished-at="2024-02-27T08:59:26 IST" duration-ms="4557" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- StartBrowser -->
        <test-method signature="Excel(java.lang.String,java.lang.String)[pri:0, instance:package_name.Login_functionality22@6771beb3]" started-at="2024-02-27T08:59:26 IST" name="Excel" data-provider="testing" finished-at="2024-02-27T08:59:30 IST" duration-ms="3572" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[standard_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[Job is done]]>
            </line>
          </reporter-output>
        </test-method> <!-- Excel -->
        <test-method signature="Excel(java.lang.String,java.lang.String)[pri:0, instance:package_name.Login_functionality22@6771beb3]" started-at="2024-02-27T08:59:30 IST" name="Excel" data-provider="testing" finished-at="2024-02-27T08:59:31 IST" duration-ms="576" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[locked_out_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Not matching expected [https://www.saucedemo.com/v1/inventory.html] but found [https://www.saucedemo.com/v1/index.html]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Not matching expected [https://www.saucedemo.com/v1/inventory.html] but found [https://www.saucedemo.com/v1/index.html]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at package_name.Login_functionality22.Excel(Login_functionality22.java:30)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Job is done]]>
            </line>
          </reporter-output>
        </test-method> <!-- Excel -->
        <test-method signature="Excel(java.lang.String,java.lang.String)[pri:0, instance:package_name.Login_functionality22@6771beb3]" started-at="2024-02-27T08:59:31 IST" name="Excel" data-provider="testing" finished-at="2024-02-27T08:59:31 IST" duration-ms="527" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[problem_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauc]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Not matching expected [https://www.saucedemo.com/v1/inventory.html] but found [https://www.saucedemo.com/v1/index.html]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Not matching expected [https://www.saucedemo.com/v1/inventory.html] but found [https://www.saucedemo.com/v1/index.html]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at package_name.Login_functionality22.Excel(Login_functionality22.java:30)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Job is done]]>
            </line>
          </reporter-output>
        </test-method> <!-- Excel -->
        <test-method signature="Excel(java.lang.String,java.lang.String)[pri:0, instance:package_name.Login_functionality22@6771beb3]" started-at="2024-02-27T08:59:31 IST" name="Excel" data-provider="testing" finished-at="2024-02-27T08:59:37 IST" duration-ms="5661" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[performance_glitch_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[Job is done]]>
            </line>
          </reporter-output>
        </test-method> <!-- Excel -->
        <test-method is-config="true" signature="closingBrowser()[pri:0, instance:package_name.Login_functionality22@6771beb3]" started-at="2024-02-27T08:59:37 IST" name="closingBrowser" finished-at="2024-02-27T08:59:38 IST" duration-ms="631" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closingBrowser -->
      </class> <!-- package_name.Login_functionality22 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
